defaultSemverRangePrefix: ""

enableGlobalCache: false

npmRegistryServer: "http://npm.kylin.shuyun.com/"

# npmRegistryServer: "http://localhost:4873/"
# unsafeHttpWhitelist:
# - localhost

unsafeHttpWhitelist:
    - npm.kylin.shuyun.com

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - ./yarn-plugins/plugin-postinstall.js
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"

yarnPath: .yarn/releases/yarn-3.3.1.cjs
