blank_issues_enabled: false
contact_links:
  - name: Question 🤷🏻‍♂️
    url: https://github.com/verdaccio/verdaccio/discussions/new?category=q-a
    about: 🆕 Open a new Q&A discussion 🙏
  - name: Security Report 🛡
    url: https://github.com/verdaccio/verdaccio/security/policy
    about: I want to report a security vulnerability
  - name: Chat 🏘
    url: http://chat.verdaccio.org
    about: For a quick question you should do it through our community chat
  - name: User Interface Report 👩🏼‍🎨👨🏼‍🎨
    url: https://github.com/verdaccio/ui/issues/new/choose
    about: Any report related with the User Interface should be posted in another repository
