name: Release Canary 5.x

on:
  workflow_dispatch:
  push:
    branches:
      - 5.x
      - 'jota/**'
      - 'canary/**'
      - '5x-refactor-test'
jobs:
  release:
    name: Release Snapshot
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # tag=v4.1.0
    - name: Use Node (latest)
      uses: actions/setup-node@1f8c6b94b26d0feae1e387ca63ccbdc44d27b561 # tag=v2.5.1
      with:
        node-version-file: '.nvmrc'
    - name: Install
      run: yarn install
    - name: Build
      run: yarn build
    - name: Bump up package
      run: npm version prerelease --no-git-tag-version --preid $(date +%s%N)      
    - name: Publish
      run: sh scripts/publish-prerelease.sh
      env:
        REGISTRY_AUTH_TOKEN: ${{ secrets.VERDACCIO_REGISTRY_TOKEN_CANARY }}
        REGISTRY_URL: registry.verdaccio.org
